In [4]:
!pip install scikit-learn

  Using cached joblib-1.5.1-py3-none-any.whl.metadata (5.6 kB)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
    --------------------------------------- 0.3/10.7 MB ? eta -:--:--
    --------------------------------------- 0.3/10.7 MB ? eta -:--:--
    --------------------------------------- 0.3/10.7 MB ? eta -:--:--
   -- ------------------------------------- 0.8/10.7 MB 842.2 kB/s eta 0:00:12
   --- ------------------------------------ 1.0/10.7 MB 962.7 kB/s eta 0:00:10
   ---- ----------------------------------- 1.3/10.7 MB 1.1 MB/s eta 0:00:09
   ----- ---------------------------------- 1.6/10.7 MB 1.1 MB/s eta 0:00:09
   ------ --------------------------------- 1.8/10.7 MB 1.1 MB/s eta 0:00:08
   ------ --------------------------------- 1.8/10.7 MB 1.1 MB/s eta 0:00:08
   ------ --------------------------------- 1.8/10.7

In [10]:
from sklearn.model_selection import KFold
import numpy as np
kf=KFold(n_splits=5,shuffle=False)
data=np.random.rand(10,10)

data
ans=[]

for i, (train, test) in enumerate(kf.split(data)):
    print(i)
    print(train)
    print(test)
    ans.append((train,test))


ans

0
[2 3 4 5 6 7 8 9]
[0 1]
1
[0 1 4 5 6 7 8 9]
[2 3]
2
[0 1 2 3 6 7 8 9]
[4 5]
3
[0 1 2 3 4 5 8 9]
[6 7]
4
[0 1 2 3 4 5 6 7]
[8 9]


[(array([2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1])),
 (array([0, 1, 4, 5, 6, 7, 8, 9]), array([2, 3])),
 (array([0, 1, 2, 3, 6, 7, 8, 9]), array([4, 5])),
 (array([0, 1, 2, 3, 4, 5, 8, 9]), array([6, 7])),
 (array([0, 1, 2, 3, 4, 5, 6, 7]), array([8, 9]))]

In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.7 MB 1.6 MB/s eta 0:00:08
   -- ------------------------------------- 0.8/12.7 MB 1.8 MB/s eta 0:00:07
   --- ------------------------------------ 1.0/12.7 MB 1.9 MB/s eta 0:00:07
   --- ------------------------------------ 1.0/12.7 MB 1.9 MB/s eta 0:00:07
   --- ------------------------------------ 1.0/12.7 MB 1.9 MB/s eta 0:00:07
   --- ------------------------------------ 1.0/12.7 MB 1.9 MB/s eta 0:00:07
   --- ------------------------------------ 1.0/12.7 MB 1.9 MB/s eta 0:00:07
   --- ------------------------------------ 1.0/12.7 MB 1.9 MB/s eta 0:00:07
   ---- ----------------------------------- 1.3/12.7 MB 597.6 kB/s eta 0:00:20
   ---- -----------------

In [ ]:
from numpy import concatenate
x=np.array([0,1,2,3,4,5,6,7,8,9])
y=np.array([0,1,2,3,4,5,6,7,8,9])


dataset = np.column_stack((x, y))
dataset




array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6],
       [7, 7],
       [8, 8],
       [9, 9]])

In [15]:
from sklearn.model_selection import KFold

kf=KFold(n_splits=5,shuffle=False)
ans=[]
for i ,(train,test) in enumerate(kf.split(dataset)):
    ans.append((train,test))


ans

[(array([2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1])),
 (array([0, 1, 4, 5, 6, 7, 8, 9]), array([2, 3])),
 (array([0, 1, 2, 3, 6, 7, 8, 9]), array([4, 5])),
 (array([0, 1, 2, 3, 4, 5, 8, 9]), array([6, 7])),
 (array([0, 1, 2, 3, 4, 5, 6, 7]), array([8, 9]))]

In [ ]:
import numpy as np

def k_fold_cross_validation(X: np.ndarray, y: np.ndarray, k=5, shuffle=True):
    """
    Implement k-fold cross-validation by returning train-test indices.
    """
    # Your code here
    dataset = np.column_stack((x, y))
    from sklearn.model_selection import KFold
    kf=KFold(n_splits=k,shuffle=shuffle)
    ans=[]
    for i ,(train,test) in enumerate(kf.split(dataset)):
        ans.append((train,test))
    return ans

In [17]:
k_fold_cross_validation(np.array([0,1,2,3,4,5,6,7,8,9]), np.array([0,1,2,3,4,5,6,7,8,9]), k=5, shuffle=False)

[(array([2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1])),
 (array([0, 1, 4, 5, 6, 7, 8, 9]), array([2, 3])),
 (array([0, 1, 2, 3, 6, 7, 8, 9]), array([4, 5])),
 (array([0, 1, 2, 3, 4, 5, 8, 9]), array([6, 7])),
 (array([0, 1, 2, 3, 4, 5, 6, 7]), array([8, 9]))]

In [34]:

x=np.array([0,1,2,3,47,5,6,70,8,90])

perm=np.random.permutation(len(x))
perm
k=2

xx=perm[k:]
x
y=perm[:k]
y,x

perm

xxx=x[perm[k:]]
xxx
# perm[k:]




array([ 6,  8, 70, 90,  3, 47,  2,  0])

In [43]:
x=[0,1,2,3,4,5,6,7,8,9]

k=2

l=int(len(x)/int(k))

ans=[]
for _ in range(k):
    perm=np.random.permutation(len(x))

    train=perm[l:]
    test=perm[:l]
    ans.append((train,test))

ans



[(array([0, 6, 3, 5, 1], dtype=int32), array([7, 4, 9, 8, 2], dtype=int32)),
 (array([9, 7, 6, 8, 4], dtype=int32), array([1, 3, 2, 0, 5], dtype=int32))]

In [51]:
def k_fold_cross_validation(X: np.ndarray, y: np.ndarray, k=5, shuffle=True):
    """
    Implement k-fold cross-validation by returning train-test indices.
    """
    # Your code here
    

    l=int(len(x)/int(k))

    ans=[]
    if shuffle==True:
        for _ in range(k):
            perm=np.random.permutation(len(x))

            train=perm[l:]
            test=perm[:l]
            ans.append((train,test))
    else:
        for _ in range(k):
            # perm=np.random.permutation(len(x))

            train=x[l:]
            test=x[:l]
            ans.append((train,test))


  


    return ans

In [49]:
k_fold_cross_validation(np.array([0,1,2,3,4,5,6,7,8,9]), np.array([0,1,2,3,4,5,6,7,8,9]), k=5, shuffle=False)

[([2, 3, 4, 5, 6, 7, 8, 9], [0, 1]),
 ([2, 3, 4, 5, 6, 7, 8, 9], [0, 1]),
 ([2, 3, 4, 5, 6, 7, 8, 9], [0, 1]),
 ([2, 3, 4, 5, 6, 7, 8, 9], [0, 1]),
 ([2, 3, 4, 5, 6, 7, 8, 9], [0, 1])]

In [ ]:
import numpy as np

def k_fold_cross_validation(X: np.ndarray, y: np.ndarray, k=5, shuffle=True):
    """
    Implement k-fold cross-validation by returning train-test indices.
    """
    n_samples = len(X)
    fold_size = n_samples // k
    indices = np.arange(n_samples)
    
    if shuffle:
        indices = np.random.permutation(indices)
    
    ans = []
    for i in range(k):
        test_start = i * fold_size
        test_end = (i + 1) * fold_size
        test_indices = indices[test_start:test_end]
        train_indices = np.concatenate([indices[:test_start], indices[test_end:]])
        ans.append((train_indices, test_indices))
    
    return ans


k-fold CV (shuffle=False):
Fold 1: Train=[2 3 4 5 6 7 8 9], Test=[0 1]
Fold 2: Train=[0 1 4 5 6 7 8 9], Test=[2 3]
Fold 3: Train=[0 1 2 3 6 7 8 9], Test=[4 5]
Fold 4: Train=[0 1 2 3 4 5 8 9], Test=[6 7]
Fold 5: Train=[0 1 2 3 4 5 6 7], Test=[8 9]

k-fold CV (shuffle=True):
Fold 1: Train=[1 5 2 7 3 4 9 8], Test=[0 6]
Fold 2: Train=[0 6 2 7 3 4 9 8], Test=[1 5]
Fold 3: Train=[0 6 1 5 3 4 9 8], Test=[2 7]
Fold 4: Train=[0 6 1 5 2 7 9 8], Test=[3 4]
Fold 5: Train=[0 6 1 5 2 7 3 4], Test=[9 8]
